import React, { useState } from "react";
import {
  Upload,
  FileText,
  RefreshCw,
  MessageCircle,
  FileSearch,
  ShieldCheck,
} from "lucide-react";
import Chatbot from "./chatbot";
import { Calendar, PlusCircle } from "lucide-react";
import { Split, CheckCircle, AlertTriangle, Clock } from "lucide-react";
import { useEffect } from "react";
import { supabase } from "../supabaseClient";
import { useNavigate } from "react-router-dom";

function Work() {
  const [file, setFile] = useState(null);
  const [extractedText, setExtractedText] = useState("");
  const [summary, setSummary] = useState("");
  const [keyClauses, setKeyClauses] = useState([]);
  const [legalObligations, setLegalObligations] = useState([]);
  const [isProcessing, setIsProcessing] = useState(false);
  const [isChatOpen, setIsChatOpen] = useState(false);
  const [error, setError] = useState(null);
  const [actions, setActions] = useState([]);
  //new
  const [mode, setMode] = useState("single"); // "single" or "compare"
  const [file2, setFile2] = useState(null);
  const [text1, setText1] = useState("");
  const [text2, setText2] = useState("");
  const [comparisonResult, setComparisonResult] = useState(null);
  const [user, setUser] = useState(null);
  const navigate = useNavigate();
  const [loadingStates, setLoadingStates] = useState({
    text: false,
    summary: false,
    clauses: false,
    obligations: false,
  });

  // Check for logged-in user on load
  useEffect(() => {
    const getUser = async () => {
      const {
        data: { session },
      } = await supabase.auth.getSession();
      if (session) {
        setUser(session.user);
      }
    };
    getUser();
  }, []);

  const handleFileUpload = (event) => {
    const uploadedFile = event.target.files?.[0];
    if (uploadedFile) {
      setFile(uploadedFile);
      setExtractedText("");
      setSummary("");
      setKeyClauses([]);
      setLegalObligations([]);
      setError(null);
      setLoadingStates({
        text: false,
        summary: false,
        clauses: false,
        obligations: false,
      });
    }
  };

  const saveToDatabase = async (analysisResult, text) => {
    if (!user) return; // Don't save if user is guest

    try {
      const { error } = await supabase.from("documents").insert([
        {
          user_id: user.id,
          file_name: file?.name || "Untitled",
          extracted_text: text, // Saving the raw text
          summary: analysisResult.summary,
          key_clauses: analysisResult.key_clauses, // Supabase handles JSON automatically
          obligations: analysisResult.obligations,
          actions: analysisResult.actions,
        },
      ]);

      if (error) {
        console.error("Supabase Save Error:", error);
      } else {
        console.log("Document saved to history!");
      }
    } catch (err) {
      console.error("Database error:", err);
    }
  };

  // Helper function to generate and download ICS file
  const addToCalendar = (action) => {
    // Format the date for ICS (YYYYMMDD)
    const dateStr = action.date.replace(/-/g, "");

    const icsContent = `BEGIN:VCALENDAR
VERSION:2.0
BEGIN:VEVENT
SUMMARY:${action.title}
DTSTART;VALUE=DATE:${dateStr}
DESCRIPTION:${action.description || "Generated by DocBrief"}
END:VEVENT
END:VCALENDAR`;

    const blob = new Blob([icsContent], { type: "text/calendar" });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.setAttribute("download", `${action.title.replace(/\s+/g, "_")}.ics`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  // Helper to upload and extract text
  const handleExtract = async (uploadedFile, setTextFn) => {
    const formData = new FormData();
    formData.append("file", uploadedFile);

    try {
      const response = await fetch("http://localhost:5000/extract_text", {
        method: "POST",
        body: formData,
      });
      const data = await response.json();
      setTextFn(data.text || "");
      return data.text;
    } catch (error) {
      console.error("Extraction failed", error);
      alert("Failed to read file.");
    }
  };

  const handleCompare = async () => {
    if (!text1 || !text2) {
      alert("Please upload both documents first.");
      return;
    }

    setIsProcessing(true);
    try {
      const response = await fetch("http://localhost:5000/compare_documents", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ text1: text1, text2: text2 }),
      });
      const data = await response.json();
      setComparisonResult(data);
    } catch (error) {
      console.error("Comparison failed", error);
    } finally {
      setIsProcessing(false);
    }
  };

  const processDocument = async () => {
    if (!file) return;

    setIsProcessing(true);
    setError(null);
    // Set all loaders to true initially
    setLoadingStates({
      text: true,
      summary: true,
      clauses: true,
      obligations: true,
    });

    const formData = new FormData();
    formData.append("file", file);

    try {
      // 1. Extract Text (Step 1)
      const textResponse = await fetch("http://localhost:5000/extract_text", {
        method: "POST",
        body: formData,
      });

      if (!textResponse.ok) throw new Error("Failed to extract text");
      const textData = await textResponse.json();
      const extracted = textData.text || "No text extracted";

      setExtractedText(extracted);
      setLoadingStates((prev) => ({ ...prev, text: false }));

      // 2. Single Analysis Call (Step 2 - The Fix)
      if (extracted && extracted !== "No text extracted") {
        const analyzeResponse = await fetch(
          "http://localhost:5000/analyze_document",
          {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ text: extracted }),
          }
        );

        if (!analyzeResponse.ok) {
          throw new Error(
            analyzeResponse.status === 429
              ? "Server is busy (Rate Limit). Please wait a moment."
              : "Analysis failed"
          );
        }

        const result = await analyzeResponse.json();

        // Update all states at once
        setSummary(result.summary || "No summary generated.");
        setKeyClauses(result.key_clauses || []);
        setLegalObligations(result.obligations || []);
        setActions(result.actions || []);
        saveToDatabase(result, extracted);
      }
    } catch (error) {
      console.error("Error processing document:", error);
      setError(error.message || "Failed to process document.");
    } finally {
      // Turn off all loaders
      setLoadingStates({
        text: false,
        summary: false,
        clauses: false,
        obligations: false,
      });
      setIsProcessing(false);
    }
  };

  const fetchData = async (endpoint, setter, key, text, loadingKey) => {
    try {
      const response = await fetch(`http://localhost:5000/${endpoint}`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ text }),
      });
      if (!response.ok) throw new Error(`Failed to fetch ${endpoint}`);
      const data = await response.json();
      setter(data[key] || []);
    } catch (error) {
      console.error(`Error fetching ${endpoint}:`, error);
      setError(`Failed to fetch ${endpoint}. Please try again.`);
    } finally {
      setLoadingStates((prev) => ({ ...prev, [loadingKey]: false }));
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-indigo-50 via-white to-purple-50 py-12 px-4">
      <div className="absolute top-6 right-6 z-10">
        <button
          onClick={() => navigate("/history")}
          className="bg-white text-gray-700 px-4 py-2 rounded-full shadow border border-gray-200 hover:bg-gray-50 flex items-center gap-2 font-medium text-sm transition"
        >
          <Clock className="w-4 h-4" /> History
        </button>
      </div>
      <div className="max-w-6xl mx-auto">
        <h1 className="text-3xl font-bold text-center mb-4 text-gray-800">
          Document Intelligence Workspace
        </h1>

        {/* --- MODE SWITCHER (TOGGLE) --- */}
        <div className="flex justify-center mb-10">
          <div className="bg-white p-1.5 rounded-full flex shadow-sm border border-gray-200">
            <button
              onClick={() => setMode("single")}
              className={`px-8 py-2.5 rounded-full text-sm font-semibold transition-all duration-300 ${
                mode === "single"
                  ? "bg-purple-600 text-white shadow-md"
                  : "text-gray-500 hover:text-purple-600"
              }`}
            >
              Single Analysis
            </button>
            <button
              onClick={() => setMode("compare")}
              className={`px-8 py-2.5 rounded-full text-sm font-semibold transition-all duration-300 ${
                mode === "compare"
                  ? "bg-blue-600 text-white shadow-md"
                  : "text-gray-500 hover:text-blue-600"
              }`}
            >
              Compare Mode
            </button>
          </div>
        </div>

        {/* ========================================================= */}
        {/* SINGLE ANALYSIS MODE                   */}
        {/* ========================================================= */}
        {mode === "single" && (
          <div className="animate-in fade-in slide-in-from-bottom-4 duration-500">
            {/* File Upload Section */}
            <div className="bg-white rounded-xl shadow-lg p-6 mb-8 transition-all hover:shadow-xl">
              <div className="border-2 border-dashed border-gray-300 rounded-lg p-10 text-center hover:border-purple-400 hover:bg-purple-50 transition-colors">
                <input
                  type="file"
                  id="fileUpload"
                  className="hidden"
                  onChange={handleFileUpload}
                  accept=".txt,.pdf,.doc,.docx,.png,.jpg,.jpeg"
                />
                <label
                  htmlFor="fileUpload"
                  className="cursor-pointer flex flex-col items-center"
                >
                  <div className="bg-purple-100 p-4 rounded-full mb-4">
                    <Upload className="h-8 w-8 text-purple-600" />
                  </div>
                  <span className="text-xl font-medium text-gray-700 mb-2">
                    Click to upload your document
                  </span>
                  <span className="text-sm text-gray-400">
                    Supported formats: PDF, PNG, JPG, TXT
                  </span>
                </label>
              </div>

              {/* Selected File & Process Button */}
              {file && (
                <div className="mt-6 p-4 bg-gray-50 rounded-lg border border-gray-200 flex flex-col sm:flex-row items-center justify-between gap-4">
                  <div className="flex items-center">
                    <div className="bg-purple-600 p-2 rounded-lg mr-3">
                      <FileText className="h-6 w-6 text-white" />
                    </div>
                    <div>
                      <p className="font-semibold text-gray-800">{file.name}</p>
                      <p className="text-xs text-gray-500">
                        {(file.size / 1024).toFixed(2)} KB
                      </p>
                    </div>
                  </div>
                  <button
                    onClick={processDocument}
                    disabled={isProcessing}
                    className="w-full sm:w-auto bg-purple-600 text-white px-6 py-2.5 rounded-lg hover:bg-purple-700 transition-all disabled:bg-purple-300 disabled:cursor-not-allowed flex items-center justify-center font-medium shadow-md hover:shadow-lg"
                  >
                    {isProcessing ? (
                      <>
                        <RefreshCw className="h-4 w-4 mr-2 animate-spin" />
                        Analyzing...
                      </>
                    ) : (
                      "Process Document"
                    )}
                  </button>
                </div>
              )}
            </div>

            {/* Error Message */}
            {error && (
              <div className="bg-red-50 border-l-4 border-red-500 text-red-700 p-4 mb-6 rounded-r shadow-sm">
                <p className="font-medium">Analysis Error</p>
                <p className="text-sm">{error}</p>
              </div>
            )}

            {/* Results Section */}
            {extractedText && (
              <div className="space-y-8">
                {/* 1. Summary */}
                <ContentBox
                  title="Executive Summary"
                  content={summary}
                  loading={loadingStates.summary}
                />

                <div className="grid md:grid-cols-2 gap-6">
                  {/* 2. Actions (Top Priority) */}
                  <ActionBox
                    items={actions}
                    loading={loadingStates.obligations}
                    onAdd={addToCalendar}
                  />

                  {/* 3. Key Clauses */}
                  <ListBox
                    title="Key Legal Clauses"
                    items={keyClauses}
                    icon={<FileSearch className="text-purple-600" />}
                    loading={loadingStates.clauses}
                  />
                </div>

                {/* 4. Obligations & Extracted Text */}
                <div className="grid md:grid-cols-2 gap-6">
                  <ListBox
                    title="Legal Obligations"
                    items={legalObligations}
                    icon={<ShieldCheck className="text-purple-600" />}
                    loading={loadingStates.obligations}
                  />
                  <ContentBox
                    title="Raw Extracted Text"
                    content={
                      extractedText.slice(0, 1000) +
                      (extractedText.length > 1000 ? "..." : "")
                    }
                    loading={loadingStates.text}
                  />
                </div>
              </div>
            )}
          </div>
        )}

        {/* ========================================================= */}
        {/* COMPARE MODE (NEW)                    */}
        {/* ========================================================= */}
        {mode === "compare" && (
          <div className="animate-in fade-in slide-in-from-bottom-4 duration-500">
            <div className="grid md:grid-cols-2 gap-8 mb-8">
              {/* Document A Upload */}
              <div
                className={`bg-white p-6 rounded-xl shadow-md border-2 border-dashed transition-all ${
                  text1 ? "border-purple-500 bg-purple-50" : "border-gray-300"
                }`}
              >
                <h3 className="font-bold text-gray-700 mb-4 text-center">
                  Document Version A
                </h3>
                <input
                  type="file"
                  onChange={(e) => handleExtract(e.target.files[0], setText1)}
                  className="block w-full text-sm text-gray-500 file:mr-4 file:py-2.5 file:px-4 file:rounded-full file:border-0 file:text-sm file:font-semibold file:bg-purple-100 file:text-purple-700 hover:file:bg-purple-200 cursor-pointer"
                />
                {text1 && (
                  <div className="mt-3 flex items-center justify-center text-green-600 bg-white p-2 rounded shadow-sm">
                    <CheckCircle className="h-4 w-4 mr-2" />
                    <span className="text-sm font-medium">
                      Ready for analysis
                    </span>
                  </div>
                )}
              </div>

              {/* Document B Upload */}
              <div
                className={`bg-white p-6 rounded-xl shadow-md border-2 border-dashed transition-all ${
                  text2 ? "border-blue-500 bg-blue-50" : "border-gray-300"
                }`}
              >
                <h3 className="font-bold text-gray-700 mb-4 text-center">
                  Document Version B
                </h3>
                <input
                  type="file"
                  onChange={(e) => handleExtract(e.target.files[0], setText2)}
                  className="block w-full text-sm text-gray-500 file:mr-4 file:py-2.5 file:px-4 file:rounded-full file:border-0 file:text-sm file:font-semibold file:bg-blue-100 file:text-blue-700 hover:file:bg-blue-200 cursor-pointer"
                />
                {text2 && (
                  <div className="mt-3 flex items-center justify-center text-green-600 bg-white p-2 rounded shadow-sm">
                    <CheckCircle className="h-4 w-4 mr-2" />
                    <span className="text-sm font-medium">
                      Ready for analysis
                    </span>
                  </div>
                )}
              </div>
            </div>

            {/* Compare Action Button */}
            <div className="text-center mb-10">
              <button
                onClick={handleCompare}
                disabled={!text1 || !text2 || isProcessing}
                className="bg-gray-900 text-white px-10 py-4 rounded-full text-lg font-semibold hover:bg-gray-800 disabled:bg-gray-300 disabled:cursor-not-allowed transition-all shadow-xl hover:shadow-2xl flex items-center gap-3 mx-auto"
              >
                {isProcessing ? (
                  <RefreshCw className="animate-spin h-5 w-5" />
                ) : (
                  <Split className="h-5 w-5" />
                )}
                Run Comparison Analysis
              </button>
            </div>

            {/* Comparison Results */}
            {comparisonResult && (
              <div className="animate-in zoom-in-95 duration-500">
                <ComparisonBox result={comparisonResult} />
              </div>
            )}
          </div>
        )}
      </div>

      {/* Floating Chat Button (Available in Single Mode mainly) */}
      <button
        className="fixed bottom-8 right-8 bg-gray-900 text-white p-4 rounded-full shadow-2xl hover:bg-gray-800 transition-transform hover:scale-110 z-50"
        onClick={() => setIsChatOpen(!isChatOpen)}
      >
        <MessageCircle className="h-6 w-6" />
      </button>

      {isChatOpen && <Chatbot context={extractedText} />}
    </div>
  );
}

// Spinner Component
const Spinner = () => (
  <div className="flex justify-center items-center h-20">
    <div className="animate-spin rounded-full h-8 w-8 border-t-2 border-b-2 border-purple-600"></div>
  </div>
);

// ContentBox Component
const ContentBox = ({ title, content, loading }) => (
  <div className="bg-white rounded-lg shadow-lg p-6">
    <h2 className="text-xl font-semibold mb-4">{title}</h2>
    <div className="bg-gray-50 p-4 rounded min-h-[96px]">
      {loading ? <Spinner /> : <p className="text-gray-700">{content}</p>}
    </div>
  </div>
);

// ListBox Component
const ListBox = ({ title, items, icon, loading }) => (
  <div className="bg-white rounded-lg shadow-lg p-6">
    <h2 className="text-xl font-semibold mb-4 flex items-center gap-2">
      {icon} {title}
    </h2>
    <div className="bg-gray-50 p-4 rounded min-h-[96px]">
      {loading ? (
        <Spinner />
      ) : (
        <ul>
          {items.map((item, index) => (
            <li key={index} className="text-gray-700 mb-2">
              {item}
            </li>
          ))}
        </ul>
      )}
    </div>
  </div>
);

const ActionBox = ({ items, loading, onAdd }) => (
  <div className="bg-white rounded-lg shadow-lg p-6 border-l-4 border-green-500">
    <h2 className="text-xl font-semibold mb-4 flex items-center gap-2 text-gray-800">
      <Calendar className="text-green-600" /> Smart Actions & Deadlines
    </h2>
    <div className="bg-gray-50 p-4 rounded min-h-[96px]">
      {loading ? (
        <Spinner />
      ) : items.length === 0 ? (
        <p className="text-gray-500 italic">
          No specific dates or deadlines found.
        </p>
      ) : (
        <div className="grid gap-4 md:grid-cols-2">
          {items.map((item, index) => (
            <div
              key={index}
              className="bg-white p-4 rounded border border-gray-200 shadow-sm flex flex-col justify-between hover:shadow-md transition"
            >
              <div>
                <div className="flex justify-between items-start">
                  <h3 className="font-bold text-gray-800">{item.title}</h3>
                  <span className="text-xs font-mono bg-green-100 text-green-800 px-2 py-1 rounded">
                    {item.date}
                  </span>
                </div>
                <p className="text-sm text-gray-600 mt-2">{item.description}</p>
              </div>
              <button
                onClick={() => onAdd(item)}
                className="mt-4 flex items-center justify-center gap-2 w-full bg-green-600 text-white py-2 rounded hover:bg-green-700 transition text-sm font-medium"
              >
                <PlusCircle size={16} /> Add to Calendar
              </button>
            </div>
          ))}
        </div>
      )}
    </div>
  </div>
);

const ComparisonBox = ({ result }) => {
  if (!result) return null;

  return (
    <div className="bg-white rounded-lg shadow-lg p-6 border-t-4 border-blue-500 mt-6">
      <h2 className="text-2xl font-bold mb-6 flex items-center gap-2 text-gray-800">
        <Split className="text-blue-600" /> Comparison Analysis
      </h2>

      {/* Verdict */}
      <div className="bg-blue-50 p-4 rounded-lg mb-6 border border-blue-100">
        <h3 className="font-bold text-blue-800 mb-1">AI Verdict</h3>
        <p className="text-blue-900">{result.verdict}</p>
      </div>

      <div className="grid md:grid-cols-2 gap-6">
        {/* Differences */}
        <div>
          <h3 className="font-semibold text-red-600 flex items-center gap-2 mb-3">
            <AlertTriangle size={20} /> Key Differences
          </h3>
          <ul className="space-y-2">
            {result.differences.map((diff, i) => (
              <li
                key={i}
                className="text-sm text-gray-700 bg-red-50 p-2 rounded"
              >
                • {diff}
              </li>
            ))}
          </ul>
        </div>

        {/* Similarities */}
        <div>
          <h3 className="font-semibold text-green-600 flex items-center gap-2 mb-3">
            <CheckCircle size={20} /> Similarities
          </h3>
          <ul className="space-y-2">
            {result.similarities.map((sim, i) => (
              <li
                key={i}
                className="text-sm text-gray-700 bg-green-50 p-2 rounded"
              >
                • {sim}
              </li>
            ))}
          </ul>
        </div>
      </div>
    </div>
  );
};

export default Work;
